---
title: "About the workshop"
format: html
---

## Part 01: Introduction to R and RStudio

Learn the fundamentals of R and RStudio, including how to set up your working directory and R projects, understand basic data types and structures in R such as vectors and data frames, and how to import data files into R.

## Part 02: Data wrangling with tidyverse

Master the basics of data manipulation with tidyverse, including how to filter, select, mutate, and group data to prepare it for analysis.

## Part 03: Data visualization and Descriptive Statistics

Learn how to create and customize data visualizations such as scatterplots, boxplots, and barplots using ggplot2. Explore methods for calculating and visualizing descriptive statistics like means, medians, and standard deviations in R.

## Part 04: Basic Inferential Tests

Discover how to conduct fundamental statistical analysis in social sciences using R, including t-tests (independent and paired samples), chi-square tests of independence, and ANOVA. Learn how to interpret and report these results.

## Part 05: Correlation, Regression, and Introduction to Quarto

Learn how to conduct correlation analysis and simple linear regression and binary logistic regression in R. Learn best practices to improve code readability and reproducibility. This session will also introduce you to Quarto, a powerful tool for creating dynamic documents that integrate R code, text, plots, and statistical output.
